# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9efc336596b2572aa6c5358239c4bb12d340751991922d557b5b3b38f5f9b9b47abae9357c2c4ade84faab22988bb9aae5c5e9060e46e070ef4510d5da7faff2

test:
  secret_key_base: 3ee4d3ba34000b63efbc653126a2270638da7facc99f3a2c05f07bf433b64c5fdfb840ee1f1a320701582fe921da3a98b7d105af7d07f013cbe1d68857720f19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
